name: TypeCheck

on: [ push, pull_request ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install --ignore-scripts # ignore prepare script which clones repository

      - name: TypeCheck
        run: tsc